import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Messenger',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, } : { children: React.ReactNode }) {

  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Providers>
          <div className='bg-black'>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
